safe: true
future: true
exclude: [.gitattributes, .gitignore, flywaydb.org.iml, flywaydb.org.ipr, flywaydb.org.iws, README.md, CNAME, Gemfile, Gemfile.lock, .idea/workspace.xml]
flywayVersion: 5.2.4
flywayPreviewVersion: 6.0.0-beta2
markdown: kramdown
url: https://flywaydb.org
kramdown:
  input: GFM
  syntax_highlighter: rouge
