safe: true
future: true
exclude: [.gitattributes, .gitignore, flywaydb.org.iml, flywaydb.org.ipr, flywaydb.org.iws, README.md, CNAME, Gemfile, Gemfile.lock]
flywayVersion: 5.1.0
markdown: kramdown
url: https://flywaydb.org
kramdown:
  input: GFM
  syntax_highlighter: rouge
